//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodooData
{
    using System;
    using System.Collections.Generic;
    
    public partial class todoo
    {
        public int id { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
